steps:
  - name: 'golang:1.23-bookworm'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['CGO_ENABLED=0']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcptoolbox:$TAG_NAME', '-t','gcr.io/$PROJECT_ID/gcptoolbox:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/gcptoolbox:$TAG_NAME' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/gcptoolbox:latest' ]
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker login ghcr.io --username=sinmetal --password=$$GITHUBPAT' ]
    secretEnv: ['GITHUBPAT']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'ghcr.io/sinmetalcraft/gcptoolbox:$TAG_NAME', '-t', 'ghcr.io/sinmetalcraft/gcptoolbox:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'ghcr.io/sinmetalcraft/gcptoolbox:$TAG_NAME' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'ghcr.io/sinmetalcraft/gcptoolbox:latest' ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-sinmetal-pat/versions/latest
    env: 'GITHUBPAT'
