steps:
  - name: 'golang:1.19-bullseye'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcptoolbox:$TAG_NAME', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/gcptoolbox:$TAG_NAME' ]
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker login ghcr.io --username=sinmetal --password=$$GITHUBPAT' ]
    secretEnv: ['GITHUBPAT']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'ghcr.io/sinmetalcraft/gcptoolbox:$TAG_NAME', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'ghcr.io/sinmetalcraft/gcptoolbox:$TAG_NAME' ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-sinmetal-pat/versions/latest
    env: 'GITHUBPAT'
