steps:
  - name: 'golang:1.16-stretch'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/kaniko-project/executor:v1.2.0'
    args:
      - --destination=gcr.io/$PROJECT_ID/gcptoolbox/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h