// Code generated by "stringer -type=BaseDate"; DO NOT EDIT.

package tables

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreationTime-0]
	_ = x[LastModifiedTime-1]
	_ = x[TableSuffix-2]
}

const _BaseDate_name = "CreationTimeLastModifiedTimeTableSuffix"

var _BaseDate_index = [...]uint8{0, 12, 28, 39}

func (i BaseDate) String() string {
	if i < 0 || i >= BaseDate(len(_BaseDate_index)-1) {
		return "BaseDate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseDate_name[_BaseDate_index[i]:_BaseDate_index[i+1]]
}
